---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600


- name: Ensure dependencies are installed
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - fontconfig
    - libasound2
    - libfuse2
    - libgl1


- name: Check install status
  ansible.builtin.stat:
    path: "{{ nextcloud_appimage }}"
  register: _nextcloud_install_status


- name: Download Nextcloud official AppImage
  become: true
  ansible.builtin.get_url:
    url: "{{ nextcloud_download_url }}"
    dest: "{{ nextcloud_appimage }}"
    mode: "0555"
  when: not _nextcloud_install_status.stat.exists


- name: Create symbolic link
  become: true
  ansible.builtin.file:
    src: "{{ nextcloud_appimage }}"
    dest: /usr/local/bin/nextcloud
    state: link
    owner: root
    group: root

