---
- name: Define Nextcloud download URL and local AppImage path
  ansible.builtin.set_fact:
    nextcloud_download_url: >
      https://github.com/nextcloud-releases/desktop/releases/download/v{{ nextcloud_version }}/Nextcloud-{{ nextcloud_version }}-x86_64.AppImage
    nextcloud_appimage: /opt/nextcloud-{{ nextcloud_version }}.AppImage

- name: Check install status
  ansible.builtin.stat:
    path: "{{ nextcloud_appimage }}"
  register: _nextcloud_install_status

- name: Download Nextcloud official AppImage
  become: true
  ansible.builtin.get_url:
    url: "{{ nextcloud_download_url }}"
    dest: "{{ nextcloud_appimage }}"
    mode: "0555"
  when: not _nextcloud_install_status.stat.exists

- name: Create symbolic link
  become: true
  ansible.builtin.file:
    src: "{{ nextcloud_appimage }}"
    dest: /usr/local/bin/nextcloud
    state: link
    owner: root
    group: root

